//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatelittiBpms.Services.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatelittiBpms.Services.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_activitySendEmailWithCustomEmail {
            get {
                object obj = ResourceManager.GetObject("diagramTest_activitySendEmailWithCustomEmail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_allTasksConnected {
            get {
                object obj = ResourceManager.GetObject("diagramTest_allTasksConnected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_endEventWithoutIncoming {
            get {
                object obj = ResourceManager.GetObject("diagramTest_endEventWithoutIncoming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_endEventWithoutIncomingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_endEventWithoutIncomingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_endEventWithoutIncomingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_endEventWithoutIncomingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayOutgoingNotHaveAssociation {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayOutgoingNotHaveAssociation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayOutgoingNotHaveAssociationAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayOutgoingNotHaveAssociationAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayOutgoingNotHaveSequenceFlow {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayOutgoingNotHaveSequenceFlow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayWithoutIncoming {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayWithoutIncoming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayWithoutIncomingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayWithoutIncomingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayWithoutIncomingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayWithoutIncomingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayWithoutOutgoing {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayWithoutOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayWithoutOutgoingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayWithoutOutgoingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_exclusiveGatewayWithoutOutgoingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_exclusiveGatewayWithoutOutgoingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_sendTaskWithoutIncoming {
            get {
                object obj = ResourceManager.GetObject("diagramTest_sendTaskWithoutIncoming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_sendTaskWithoutIncomingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_sendTaskWithoutIncomingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_sendTaskWithoutIncomingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_sendTaskWithoutIncomingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_sendTaskWithoutOutgoing {
            get {
                object obj = ResourceManager.GetObject("diagramTest_sendTaskWithoutOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_sendTaskWithoutOutgoingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_sendTaskWithoutOutgoingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_sendTaskWithoutOutgoingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_sendTaskWithoutOutgoingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_ssignIntegrationTaskWithoutIncoming {
            get {
                object obj = ResourceManager.GetObject("diagramTest_ssignIntegrationTaskWithoutIncoming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_ssignIntegrationTaskWithoutOutgoing {
            get {
                object obj = ResourceManager.GetObject("diagramTest_ssignIntegrationTaskWithoutOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_ssignIntegrationTaskWithTwoOutgoing {
            get {
                object obj = ResourceManager.GetObject("diagramTest_ssignIntegrationTaskWithTwoOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_startEventWithoutOutgoing {
            get {
                object obj = ResourceManager.GetObject("diagramTest_startEventWithoutOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_userTaskWithoutIncoming {
            get {
                object obj = ResourceManager.GetObject("diagramTest_userTaskWithoutIncoming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_userTaskWithoutIncomingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_userTaskWithoutIncomingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_userTaskWithoutIncomingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_userTaskWithoutIncomingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_userTaskWithoutOutgoing {
            get {
                object obj = ResourceManager.GetObject("diagramTest_userTaskWithoutOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_userTaskWithoutOutgoingAndName {
            get {
                object obj = ResourceManager.GetObject("diagramTest_userTaskWithoutOutgoingAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_userTaskWithoutOutgoingAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("diagramTest_userTaskWithoutOutgoingAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_withMoreThanOneStartEvent {
            get {
                object obj = ResourceManager.GetObject("diagramTest_withMoreThanOneStartEvent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_withMoreThanOneStartEventPath {
            get {
                object obj = ResourceManager.GetObject("diagramTest_withMoreThanOneStartEventPath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_withoutEndEvent {
            get {
                object obj = ResourceManager.GetObject("diagramTest_withoutEndEvent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] diagramTest_withoutStartEvent {
            get {
                object obj = ResourceManager.GetObject("diagramTest_withoutStartEvent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] formContent {
            get {
                object obj = ResourceManager.GetObject("formContent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] formContentExpected {
            get {
                object obj = ResourceManager.GetObject("formContentExpected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withoutDestinataryId {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withoutDestinataryId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withoutDestinataryIdAndName {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withoutDestinataryIdAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withoutDestinataryIdAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withoutDestinataryIdAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withoutDestinataryType {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withoutDestinataryType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withoutDestinataryTypeAndName {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withoutDestinataryTypeAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withoutDestinataryTypeAndNameId {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withoutDestinataryTypeAndNameId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withRequesterDestinatary {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withRequesterDestinatary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withRoleDestinatary {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withRoleDestinatary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] sendTaskTest_withTwoOutgoing {
            get {
                object obj = ResourceManager.GetObject("sendTaskTest_withTwoOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutExecutorId {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutExecutorId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutExecutorIdAndName {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutExecutorIdAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutExecutorIdAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutExecutorIdAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutExecutorTypeAssocieted {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutExecutorTypeAssocieted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutExecutorTypeAssocietedAndName {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutExecutorTypeAssocietedAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutExecutorTypeAssocietedAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutExecutorTypeAssocietedAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutOptionAssocieted {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutOptionAssocieted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutOptionAssocietedAndName {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutOptionAssocietedAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutOptionAssocietedAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutOptionAssocietedAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutOptionsAssocieted {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutOptionsAssocieted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutOptionsAssocietedAndName {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutOptionsAssocietedAndName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withoutOptionsAssocietedAndNameAndId {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withoutOptionsAssocietedAndNameAndId", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withRequesterExecutorAndOptionAssocieted {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withRequesterExecutorAndOptionAssocieted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withRoleExecutorAndOptionAssocieted {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withRoleExecutorAndOptionAssocieted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] userTaskTest_withTwoOutgoing {
            get {
                object obj = ResourceManager.GetObject("userTaskTest_withTwoOutgoing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] xmlServiceTest_compleDiagram {
            get {
                object obj = ResourceManager.GetObject("xmlServiceTest_compleDiagram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] xmlServiceTest_diagramWithGateway {
            get {
                object obj = ResourceManager.GetObject("xmlServiceTest_diagramWithGateway", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
